_BASE_: "../templates/4x_template.yaml"
MODEL:
  META_ARCHITECTURE: "GeneralizedUnrolledCNN"
  UNROLLED:
    NUM_UNROLLED_STEPS: 8
    NUM_RESBLOCKS: 2
    NUM_FEATURES: 128
    NUM_EMAPS: 1
    DROPOUT: 0.
    CONV_BLOCK:
      ACTIVATION: "relu"
      NORM: "none"
      ORDER: ("act", "conv")
  RECON_LOSS:
    NAME: "l1"
    RENORMALIZE_DATA: False
SOLVER:
  LR_SCHEDULER_NAME: ""
  TRAIN_BATCH_SIZE: 2
  TEST_BATCH_SIZE: 12
  MAX_ITER: 60000  # 60k iterations
  GAMMA: 1.0
  STEPS: ()  # ensures learning rate does not decay
  BASE_LR: 1e-4
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 0
  GRAD_ACCUM_ITERS: 4
  CHECKPOINT_PERIOD: -1
TEST:
  EVAL_PERIOD: -1
VIS_PERIOD: 400
TIME_SCALE: "iter"

# To set in experiment configs that inherit from this template
DESCRIPTION:
  BRIEF: ""
  EXP_NAME: ""
  TAGS: ()
OUTPUT_DIR: "" # Use prefix "results://fastmri_knee_mc_mini/unrolled-v1_4x/"