_BASE_: "template.yaml"
MODEL:
  META_ARCHITECTURE: "GeneralizedUnrolledCNN"
  UNROLLED:
    NUM_UNROLLED_STEPS: 8
    NUM_RESBLOCKS: 2
    NUM_FEATURES: 128
    DROPOUT: 0.
    CONV_BLOCK:
      ACTIVATION: "relu"
      NORM: "none"
      ORDER: ("act", "conv")
SOLVER:
  OPTIMIZER: "Adam"
  LR_SCHEDULER_NAME: ""
  TRAIN_BATCH_SIZE: 4
  GRAD_ACCUM_ITERS: 4
  TEST_BATCH_SIZE: 12
  BASE_LR: 1e-4
OUTPUT_DIR: "results://mri-recon/mridata-3dfse-knee/unrolled"
VERSION: 1