DESCRIPTION:
 BRIEF: Aug2Recon 16x mridata nm2r heavy
 EXP_NAME: mridata/nm2r_heavy/unet_16x
 PROJECT_NAME: aug2recon
DATASETS:
 TRAIN: ("mridata_knee_2019_train",)
 VAL: ("mridata_knee_2019_val",)
 TEST: ("mridata_knee_2019_test",)
AUG_TRAIN:
 UNDERSAMPLE:
   NAME: "PoissonDiskMaskFunc"
   ACCELERATIONS: (16,)
   CALIBRATION_SIZE: 20
AUG_TEST:
 UNDERSAMPLE:
   ACCELERATIONS: (16,)
DATALOADER:
 NUM_WORKERS: 8
 SUBSAMPLE_TRAIN:
   NUM_TOTAL: 6
   NUM_UNDERSAMPLED: 5
 SAMPLER_TRAIN: "AlternatingSampler"
MODEL:
 META_ARCHITECTURE: "NM2RModel"
 UNET:
   CHANNELS: 32
   DROPOUT: 0.0
   IN_CHANNELS: 2
   NUM_POOL_LAYERS: 4
   OUT_CHANNELS: 2
 RECON_LOSS:
   NAME: "l1"
   RENORMALIZE_DATA: False
 NM2R:
   META_ARCHITECTURE: "UnetModel"
 CONSISTENCY:
   AUG:
    NOISE:
      STD_DEV: (0.2,0.5)
    MOTION:
      RANGE: (0.2,0.5)
SOLVER:
 OPTIMIZER: "Adam"
 LR_SCHEDULER_NAME: ""
 TRAIN_BATCH_SIZE: 24
 TEST_BATCH_SIZE: 24
 CHECKPOINT_PERIOD: -10
 MAX_ITER: -200
 BASE_LR: 0.001
 STEPS: ()
TEST:
 EVAL_PERIOD: -10
 VAL_METRICS:
   RECON: ("psnr", "psnr_scan", "psnr_mag", "psnr_mag_scan", "nrmse", "nrmse_scan", "nrmse_mag", "nrmse_mag_scan", "ssim_old", "ssim (Wang)")
TIME_SCALE: "iter"
OUTPUT_DIR: "results://aug2recon/mridata/nm2r_heavy/unet-16x"
SEED: 1000
VIS_PERIOD: 400
VERSION: 1