
version: 2

python:
  version: 3.8
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
    - method: setuptools
      path: meddlr

sphinx:
  builder: html
  fail_on_warning: false
