_BASE_: "template_sub-1.yaml"
DATALOADER:
  SUBSAMPLE_TRAIN:
    NUM_UNDERSAMPLED: 12  # 12 undersampled scan, 2 fully sampled
DESCRIPTION:
  BRIEF: "N2R 12x mridata.org w/ Noise augmentation - 2 subject"
  EXP_NAME: "mridata_knee_2019/n2r_12x_aug"
  TAGS: ("mridata_knee_2019", "n2r_12x", "noise_aug")
OUTPUT_DIR: "results://prelim-exps/n2r_12x_aug"
VERSION: 1