# Template for fastMRI multicoil knee dataset (acceleration 4x)
#
# Acceleration: 4x
# Sampling Method: Random 1D sampling; keep center 4% of phase encode
# Max Epochs: 30
# Learning Rate: 1e-4
# Gradient Accumulation: None
MODEL:
  RECON_LOSS:
    NAME: "l1"
    RENORMALIZE_DATA: False
AUG_TRAIN:
  UNDERSAMPLE:
    NAME: "RandomMaskFunc1D"
    ACCELERATIONS: (4,)
    CALIBRATION_SIZE: 0
    CENTER_FRACTIONS: (0.04,)
AUG_TEST:
  UNDERSAMPLE:
    ACCELERATIONS: (4,)
DATASETS:
  TRAIN: ("fastMRI_knee_multicoil_mini_v0.0.1_train",)
  VAL: ("fastMRI_knee_multicoil_mini_v0.0.1_val",)
  TEST: ("fastMRI_knee_multicoil_mini_v0.0.1_test",)
DATALOADER:
  DATA_KEYS: (("target", "jsense-8/target"), ("maps", "jsense-8/maps"))
  SUBSAMPLE_TRAIN:
    # change NUM_TOTAL to control how many scans should be included for training. 
    # `-1` -> all scans will be included
    NUM_TOTAL: -1
    SEED: 1000
  NUM_WORKERS: 8
SOLVER:
  OPTIMIZER: "Adam"
  LR_SCHEDULER_NAME: ""  # do not decrease learning rate.
  TRAIN_BATCH_SIZE: 2
  TEST_BATCH_SIZE: 12
  MAX_ITER: 30
  GAMMA: 1.0 # do not decrease learning rate.
  STEPS: ()  # ensures learning rate does not decay
  BASE_LR: 1e-4
  BIAS_LR_FACTOR: 1.0
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_BIAS: 0.0001
  CHECKPOINT_PERIOD: 1
  GRAD_ACCUM_ITERS: 1
TEST:
  EVAL_PERIOD: 1
VIS_PERIOD: -400
TIME_SCALE: "epoch"
OUTPUT_DIR: ""  # leave empty
SEED: 1000
VERSION: 1