# N2R with alternating sampler
# The alternating sampler switches between periods of supervised examples and unsupervised examples
_BASE_: "template.yaml"
DATALOADER:
  SAMPLER_TRAIN: "AlternatingSampler"
  ALT_SAMPLER:
    PERIOD_UNSUPERVISED: 1
    PERIOD_SUPERVISED: 1
DESCRIPTION:
  BRIEF: "N2R with alternate sampling"
  EXP_NAME: "n2r_search/alt_sampler"
  TAGS: ("n2r". "mridata_knee_2019", "alt_sampler")
OUTPUT_DIR: "results://n2r-experiments/alt_sampler"
VERSION: 1