# Very basic template for architecture search.
# All experiments are trained for 40000 epochs with a base learning rate of 1e-4
# Checkpoint and eval every 1 epoch.
# Acceleration factor: 6x
#
# Model: All config params for unrolled model should be defined in the appropriate config
#
# Seeds:
# - General: 1000
# - DataLoader: 1000
MODEL:
  META_ARCHITECTURE: "GeneralizedUnrolledCNN"
  RECON_LOSS:
    NAME: "l1"
    RENORMALIZE_DATA: True
DATASETS:
  TRAIN: ("mridata_knee_2019_train",)
  VAL: ("mridata_knee_2019_val",)
  TEST: ("mridata_knee_2019_test",)
DATALOADER:
  SUBSAMPLE_TRAIN:
    NUM_TOTAL: -1
    SEED: 1000
  NUM_WORKERS: 4
AUG_TRAIN:
  UNDERSAMPLE:
    ACCELERATIONS: (6,)
AUG_TEST:
  UNDERSAMPLE:
    ACCELERATIONS: (6,)
SOLVER:
  OPTIMIZER: "Adam"
  LR_SCHEDULER_NAME: ""
  TRAIN_BATCH_SIZE: 2
  TEST_BATCH_SIZE: 4
  MAX_ITER: 160000
  GAMMA: 1.0  # do not decrease learning rate.
  STEPS: ()
  BASE_LR: 1e-4
  BIAS_LR_FACTOR: 1.0
  CHECKPOINT_PERIOD: -1
TEST:
  EVAL_PERIOD: -1
VIS_PERIOD: 400
TIME_SCALE: "iter"
OUTPUT_DIR: ""  # template should not have an output directory
SEED: 1000
VERSION: 1