# Inherit fields from the unet.yaml config.
_BASE_: "../../templates/unet_aug.yaml"
# DATALOADER has 14 supervised scans
DATALOADER:
  SUBSAMPLE_TRAIN:
    NUM_TOTAL: 14
    NUM_UNDERSAMPLED: 0
# Specify an output directory that is unique for this experiment.
OUTPUT_DIR: results://vortex-rm/mridata_knee_3dfse/unet/supervised/supervised_aug_unet_14_scan
DESCRIPTION:
  # Use f-strings to specify reading values in braces ({}) the config file.
  # This can only be done for string fields.
  BRIEF: f"Supervised Aug U-Net 14 Scan {AUG_TRAIN.UNDERSAMPLE.ACCELERATIONS}x mridata - loss={MODEL.RECON_LOSS.NAME}" 
  EXP_NAME: mridata_knee_3dfse/unet/supervised_aug_unet_14
  TAGS:
  - baseline
  - supervised
  - 14_scan
  - 16x
  - mridata_knee_3dfse
  - unet
# For no motion aug, A2R and Consistency was removed.
# For UNET, kept META_ARCHITECTURE as UnetModel
MODEL:
  META_ARCHITECTURE: UnetModel  
  RECON_LOSS:
    NAME: l1
    RENORMALIZE_DATA: false
VERSION: 1