# Configuration for DL-CS Paper
_BASE_: "template_aug.yaml"
MODEL:
  META_ARCHITECTURE: "UnetModel"
  UNET:
    IN_CHANNELS: 2
    OUT_CHANNELS: 2
    CHANNELS: 32
    NUM_POOL_LAYERS: 4
    DROPOUT: 0.
SOLVER:
  TRAIN_BATCH_SIZE: 16
  TEST_BATCH_SIZE: 16
  BASE_LR: 1e-3