_BASE_: "template.yaml"
DATALOADER:
  SUBSAMPLE_TRAIN:
    NUM_TOTAL: -1
DESCRIPTION:
  BRIEF: "Baseline (acceleration 6x) experiments with mridata.org 3D FSE dataset - 14 (all) subjects"
  EXP_NAME: "mridata_knee_2019/baseline_6x/full"
  TAGS: ("mridata_knee_2019", "unrolled", "baseline_6x")
OUTPUT_DIR: "results://prelim-exps/baseline_6x/full"
VERSION: 1
