_BASE_: "../baseline_template.yaml"
MODEL:
  CONSISTENCY:
    AUG:
      NOISE:
        STD_DEV: (1,)
AUG_TRAIN:
  UNDERSAMPLE:
    ACCELERATIONS: (6,)
AUG_TEST:
  UNDERSAMPLE:
    ACCELERATIONS: (6,)
DATALOADER:
  SUBSAMPLE_TRAIN:
    NUM_TOTAL: 2
OUTPUT_DIR: "results://prelim-exps/baseline_6x/sub2"
VERSION: 1