_BASE_: "template.yaml"
DATALOADER:
  SUBSAMPLE_TRAIN:
    NUM_TOTAL: 2
DESCRIPTION:
  BRIEF: "Baseline (acceleration 6x) experiments with mridata.org 3D FSE dataset - 2 subjects"
  EXP_NAME: "mridata_knee_2019/baseline_6x/sub-2"
  TAGS: ("mridata_knee_2019", "unrolled", "baseline_6x")
OUTPUT_DIR: "results://prelim-exps/baseline_6x/sub-2"
VERSION: 1