# Notes:
#   - Loss is too low when renormalization is True
_BASE_: "../templates/4x_template.yaml"
MODEL:
  META_ARCHITECTURE: "GeneralizedUnrolledCNN"
  UNROLLED:
    NUM_UNROLLED_STEPS: 8
    NUM_RESBLOCKS: 2
    NUM_FEATURES: 128
    NUM_EMAPS: 1
    DROPOUT: 0.
    CONV_BLOCK:
      ACTIVATION: "relu"
      NORM: "none"
      ORDER: ("act", "conv")
  RECON_LOSS:
    NAME: "l1"
    RENORMALIZE_DATA: True
SOLVER:
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  TRAIN_BATCH_SIZE: 2
  TEST_BATCH_SIZE: 12
  MAX_ITER: 30
  GAMMA: 0.7
  STEPS: (10, 20)  # ensures learning rate does not decay
  BASE_LR: 1e-4
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 0
  GRAD_ACCUM_ITERS: 16
OUTPUT_DIR: "results://fastmri_knee_mc_mini/hyperparam_search/config-01"
DESCRIPTION:
  BRIEF: "8x unrolled network, 2 blocks, 128 channels, 2x16 grad accum, 30 epochs, step decay at 10/20 epochs, lr=1e-4, renormalize data"
  EXP_NAME: "fastmri_knee_mc_mini/hyperparam_search/config-01"
  TAGS: ("fastmri_knee_mc_mini", "hyperparameter_search")
VERSION: 1