_BASE_: "config-02.yaml"
SOLVER:
  LR_SCHEDULER_NAME: ""
  TRAIN_BATCH_SIZE: 2
  TEST_BATCH_SIZE: 12
  MAX_ITER: 30
  GAMMA: 1.0
  STEPS: ()  # ensures learning rate does not decay
  BASE_LR: 1e-4
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 0
  GRAD_ACCUM_ITERS: 16
OUTPUT_DIR: "results://fastmri_knee_mc_mini/hyperparam_search/config-03"
DESCRIPTION:
  BRIEF: "8x unrolled network, 2 blocks, 128 channels, 2x16 grad accum, 30 epochs, lr=1e-4, no scheduler, no renormalize data"
  EXP_NAME: "fastmri_knee_mc_mini/hyperparam_search/config-03"
  TAGS: ("fastmri_knee_mc_mini", "hyperparameter_search")
VERSION: 1