_BASE_: "config-03.yaml"
SOLVER:
  GRAD_ACCUM_ITERS: 8
OUTPUT_DIR: "results://fastmri_knee_mc_mini/hyperparam_search/config-05"
DESCRIPTION:
  BRIEF: "8x unrolled network, 2 blocks, 128 channels, 2x8 grad accum, 30 epochs, lr=1e-4, no scheduler, no renormalize data"
  EXP_NAME: "fastmri_knee_mc_mini/hyperparam_search/config-05"
  TAGS: ("fastmri_knee_mc_mini", "hyperparameter_search")
VERSION: 1