# Shared/default properties between different configs for the 3d fse mridata knee dataset.
AUG_TRAIN:
  UNDERSAMPLE:
    NAME: "RandomMaskFunc1D"
    ACCELERATIONS: (8,)
    CALIBRATION_SIZE: 0
    CENTER_FRACTIONS: (0.04,)
AUG_TEST:
  UNDERSAMPLE:
    ACCELERATIONS: (8,)
MODEL:
  RECON_LOSS:
    NAME: "l1"
    RENORMALIZE_DATA: False
DATASETS:
  TRAIN: ("fastMRI_knee_multicoil_v0.0.1_train",)
  VAL: ("fastMRI_knee_multicoil_v0.0.1_val",)
  TEST: ("fastMRI_knee_multicoil_v0.0.1_test",)
DATALOADER:
  DROP_LAST: True
  NUM_WORKERS: 8
  # Change these keys to match your h5 files.
  DATA_KEYS: (("target", "espirit-cf=4/target"), ("maps", "espirit-cf=4/maps"))
SOLVER:
  OPTIMIZER: "Adam"
  LR_SCHEDULER_NAME: ""
  CHECKPOINT_PERIOD: 10  # Checkpoint every 10 epochs
  MAX_ITER: 200  # Max number of epochs to train for
TEST:
  EVAL_PERIOD: 10  # Run validation every 10 epochs
  VAL_METRICS:
    RECON: ("psnr", "psnr_scan", "psnr_mag", "psnr_mag_scan", "nrmse", "nrmse_scan", "nrmse_mag", "nrmse_mag_scan", "ssim (Wang)")
TIME_SCALE: "epoch"
SEED: 1000
VIS_PERIOD: -400  # save images every 400 iterations
VERSION: 1
