DESCRIPTION:
  BRIEF: Unrolled (8 steps, 2 resblocks, 128 features) LR = 1e-4 MRS 4x fastMRI brain-mc mini - {exp_type} experiment
  EXP_NAME: fastMRI_brain_mc_mini/unrolled_8-2-256_4x
  PROJECT_NAME: mrs
  TAGS:
  - fastMRI_brain_multicoil_mini_v0.0.1
  - unrolled_4x
  - unrolled_8-2b-128f_LR1e-4
  - mrs_4x
DATASETS:
  TRAIN: ("fastMRI_brain_multicoil_mini_v0.0.1_train",)
  VAL: ("fastMRI_brain_multicoil_mini_v0.0.1_val",)
  TEST: ("fastMRI_brain_multicoil_mini_v0.0.1_test",)
AUG_TRAIN:
  UNDERSAMPLE:
    NAME: "RandomMaskFunc1D"
    ACCELERATIONS: (4,)
    CALIBRATION_SIZE: 0
    CENTER_FRACTIONS: (0.08,)
AUG_TEST:
  UNDERSAMPLE:
    ACCELERATIONS: (4,)
DATALOADER:
  NUM_WORKERS: 8
  DATA_KEYS: (("target", "espirit-cf=8/target"), ("maps", "espirit-cf=8/maps"))
  FILTER:
    BY: (("acquisition", "AXT2"),)
  SAMPLER_TRAIN: "GroupSampler"
  GROUP_SAMPLER:
    BATCH_BY: ("receiverChannels", "inplane_shape")
    AS_BATCH_SAMPLER: True
MODEL:
  META_ARCHITECTURE: "GeneralizedUnrolledCNN"
  UNROLLED:
    NUM_UNROLLED_STEPS: 8
    NUM_RESBLOCKS: 2
    NUM_FEATURES: 128
    NUM_EMAPS: 1
    DROPOUT: 0.
    CONV_BLOCK:
      ACTIVATION: "relu"
      NORM: "none"
      ORDER: ("act", "conv")
  RECON_LOSS:
    NAME: "l1"
    RENORMALIZE_DATA: False
SOLVER:
  OPTIMIZER: "Adam"
  LR_SCHEDULER_NAME: ""
  TRAIN_BATCH_SIZE: 2  # maximum batch size fitting on 11GB GPU
  GRAD_ACCUM_ITERS: 6
  TEST_BATCH_SIZE: 8
  CHECKPOINT_PERIOD: -10 # cpt every 10 epochs.
  MAX_ITER: -200
  BASE_LR: 0.0001
  STEPS: ()
TEST:
  EVAL_PERIOD: -10 # eval every 10 epochs.
  VAL_METRICS:
    RECON: ("psnr", "psnr_scan", "psnr_mag", "psnr_mag_scan", "nrmse", "nrmse_scan", "nrmse_mag", "nrmse_mag_scan", "ssim_old", "ssim (Wang)")
TIME_SCALE: "iter"
OUTPUT_DIR: "results://mrs/fastmri_brain_mc_mini/unrolled-4x"
SEED: 1000
VIS_PERIOD: 400
VERSION: 1