MODEL:
  META_ARCHITECTURE: "GeneralizedUnrolledCNN"
  UNROLLED:
    NUM_UNROLLED_STEPS: 8
    NUM_RESBLOCKS: 2
    NUM_FEATURES: 128
    NUM_EMAPS: 1
    DROPOUT: 0.
    CONV_BLOCK:
      ACTIVATION: "relu"
      NORM: "none"
      ORDER: ("act", "conv")
  WEIGHTS: "results://model-exps/denoising/model_final.pth"
  RECON_LOSS:
    NAME: "l1"
    RENORMALIZE_DATA: False
AUG_TRAIN:
  UNDERSAMPLE:
    ACCELERATIONS: (6,)
AUG_TEST:
  UNDERSAMPLE:
    ACCELERATIONS: (6,)
DATASETS:
  TRAIN: ("mridata_knee_2019_train",)
  VAL: ("mridata_knee_2019_val",)
  TEST: ("mridata_knee_2019_test",)
DATALOADER:
  SUBSAMPLE_TRAIN:
    NUM_TOTAL: -1
    SEED: 1000
  NUM_WORKERS: 4
SOLVER:
  OPTIMIZER: "Adam"
  LR_SCHEDULER_NAME: ""
  TRAIN_BATCH_SIZE: 1
  TEST_BATCH_SIZE: 4
  MAX_ITER: 160000 #80000 from pre-train, 80000 for recon
  GAMMA: 1.0  # do not decrease learning rate.
  STEPS: (80000,)  # ensures learning rate does not decay
  BASE_LR: 1e-4
  BIAS_LR_FACTOR: 1.0
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_BIAS: 0.0001
  CHECKPOINT_PERIOD: -1
DESCRIPTION:
  BRIEF: "8x unrolled network, 2 blocks, 128 channels w/ den2r using baseline configs"
  EXP_NAME: "mridata_knee_2019/den2r/8x_feat-128"
  TAGS: ("mridata_knee_2019", "unrolled")
TEST:
  EVAL_PERIOD: -1
VIS_PERIOD: 400
TIME_SCALE: "iter"
OUTPUT_DIR: ""
SEED: 1000
VERSION: 1