# Configuration for DL-CS Paper
MODEL:
  META_ARCHITECTURE: "GeneralizedUnrolledCNN"
  UNROLLED:
    NUM_UNROLLED_STEPS: 4
    NUM_RESBLOCKS: 3
    NUM_FEATURES: 128
    DROPOUT: 0.
    CONV_BLOCK:
      ACTIVATION: "relu"
      NORM: "batch"
      ORDER: ("norm", "act", "conv")
  RECON_LOSS:
    NAME: "l1"
    RENORMALIZE_DATA: False
DATASETS:
  TRAIN: ("mridata_knee_2019_train",)
  VAL: ("mridata_knee_2019_val",)
  TEST: ("mridata_knee_2019_test",)
DATALOADER:
  NUM_WORKERS: 4
SOLVER:
  OPTIMIZER: "Adam"
  LR_SCHEDULER_NAME: "StepLR"
  TRAIN_BATCH_SIZE: 2
  TEST_BATCH_SIZE: 4
  CHECKPOINT_PERIOD: 1
  MAX_ITER: 25
  BASE_LR: 0.01
  STEPS: (40000,)  # set steps so high it is never reached.
TEST:
  EVAL_PERIOD: 1
TIME_SCALE: "epoch"
OUTPUT_DIR: "results://basic/dl-cs-paper"
SEED: 1000
VIS_PERIOD: 400  # save images every 400 iterations
VERSION: 1