_BASE_: "template.yaml"
MODEL:
  RECON_LOSS:
    RENORMALIZE_DATA: False
OUTPUT_DIR: "results://fastmri_knee_mc_mini/unet/hyperparam_search/config-01"
DESCRIPTION:
  BRIEF: "32 channel u-net, 2x16 grad accum, 30 epochs, step decay at 10/20 epochs, lr=1e-4, no renormalize data"
  EXP_NAME: "fastmri_knee_mc_mini/unet_search/config-01"
  TAGS: ("fastmri_knee_mc_mini", "unet","hyperparameter_search")
VERSION: 1