_BASE_: "template.yaml"
MODEL:
    UNET:
        CHANNELS: 128
DATALOADER:
  SUBSAMPLE_TRAIN:
    NUM_TOTAL: 10
OUTPUT_DIR: "results://fastmri_knee_mc_mini/unet-v1_4x/baseline/sub-10_config03"
DESCRIPTION:
  BRIEF: "10 subjects, 128 channel u-net, train batch size 1, 2x16 grad accum, 60k iters, step decay at 10/20 epochs, lr=1e-4, no renormalize data"
  EXP_NAME: "fastmri_knee_mc_mini/unet/baseline/sub-10_config03"
  TAGS: ("fastmri_knee_mc_mini", "unet","baseline","sub10")
VERSION: 1