# Configuration for DL-CS Paper
MODEL:
  META_ARCHITECTURE: "UnetModel"
  UNET:
    IN_CHANNELS: 2
    OUT_CHANNELS: 2
    CHANNELS: 32
    NUM_POOL_LAYERS: 4
    DROPOUT: 0.
  RECON_LOSS:
    NAME: "l1"
    RENORMALIZE_DATA: False
DATASETS:
  TRAIN: ("mridata_knee_2019_train",)
  VAL: ("mridata_knee_2019_val",)
  TEST: ("mridata_knee_2019_test",)
DATALOADER:
  NUM_WORKERS: 1
SOLVER:
  OPTIMIZER: "Adam"
  LR_SCHEDULER_NAME: "StepLR"
  TRAIN_BATCH_SIZE: 1
  TEST_BATCH_SIZE: 1
  CHECKPOINT_PERIOD: -1
  MAX_ITER: 40000
  BASE_LR: 0.01
  STEPS: (40000,)  # set steps so high it is never reached.
TEST:
  EVAL_PERIOD: -1
TIME_SCALE: "iter"
OUTPUT_DIR: "results://model-exps/u-net"
SEED: 1000
VIS_PERIOD: 400  # save images every 400 iterations
VERSION: 1