# Template for subsampled training experiments using dl-recon setup.
# All experiments are trained for 40000 epochs with a base learning rate of 1e-4
# Checkpoint and eval every 1 epoch
#
# Model: 
# - Unrolled network with 15 unrolled steps
# - Each step has 2 resblocks
# - conv blocks are conv -> relu (no normalization)
_BASE_: "../basic/no_image_renormalization.yaml"
MODEL:
  UNROLLED:
    NUM_UNROLLED_STEPS: 15
    NUM_RESBLOCKS: 2
    NUM_FEATURES: 256
    NUM_EMAPS: 1
  RECON_LOSS:
    NAME: "l1"
    RENORMALIZE_DATA: False
DATALOADER:
  SUBSAMPLE_TRAIN:
    # change NUM_TOTAL to control how many scans should be included for training. 
    # `-1` -> all scans will be included
    NUM_TOTAL: -1
    SEED: 1000
SOLVER:
  MAX_ITER: 40000
  STEPS: (80000,)  # ensures learning rate does not decay
  BASE_LR: 1e-4
  BIAS_LR_FACTOR: 1.0
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_BIAS: 0.0001
  CHECKPOINT_PERIOD: -1
TEST:
  EVAL_PERIOD: -1
TIME_SCALE: "iter"
OUTPUT_DIR: ""  # template should not have an output directory
SEED: 1000
VERSION: 1