# Inherit fields from the unet.yaml config.
_BASE_: "../../templates/unet.yaml"
DATALOADER:
  SUBSAMPLE_TRAIN:
    # 1 supervised and 13 unsupervised scans for training.
    NUM_TOTAL: 14
    NUM_UNDERSAMPLED: 13
# Specify an output directory that is unique for this experiment.
OUTPUT_DIR: results://vortex-rm/mridata_knee_3dfse/unet/ssdu/ssdu_unet_13_scan
DESCRIPTION:
  # Use f-strings to specify reading values in braces ({}) the config file.
  # This can only be done for string fields.
  BRIEF: f"SSDU U-Net {AUG_TRAIN.UNDERSAMPLE.ACCELERATIONS}x mridata - {MODEL.SSDU.MASKER.PARAMS.kind}/loss={MODEL.RECON_LOSS.NAME}"
  EXP_NAME: mridata_knee_3dfse/unet/ssdu
  TAGS:
  - baseline
  - ssdu
  - 16x
  - mridata_knee_3dfse
  - unet
MODEL:
  META_ARCHITECTURE: SSDUModel
  RECON_LOSS:
    NAME: k_l1
    RENORMALIZE_DATA: false
  SSDU:
    # For UNET, the META_ARCHITECTURE of SSDUModel is UnetModel.
    META_ARCHITECTURE: UnetModel
    MASKER:
      # These parameters were taken from the VORTEX/Noise2Recon papers.
      PARAMS:
        kind: uniform
        p: 1.0
        rhos: 0.4  # Default value in SSDU code
        per_example: true 
VERSION: 1