_BASE_: "sub-1_stddev-1.yaml"
MODEL:
  CONSISTENCY:
    AUG:
      NOISE:
        STD_DEV: (0.05,)
DATALOADER:
  SUBSAMPLE_TRAIN:
    NUM_UNDERSAMPLED: 13  # 4 undersampled, 10 fully sampled
  NUM_WORKERS: 12
SOLVER:
  TRAIN_BATCH_SIZE: 2
  GRAD_ACCUM_ITERS: 4
TEST:
  VAL_AS_TEST: True
DESCRIPTION:
  BRIEF: "N2R 12x - 1 subjects (sigma=0.05)"
  EXP_NAME: "mridata_knee_2019/n2r_12x/sub-1_stddev-0.05"
  TAGS: ("n2r", "mridata_knee_2019")
OUTPUT_DIR: "results://prelim-exps/n2r_12x/sub-1_stddev-0.05"
VERSION: 1