# Requires at minimum 24GB gpu
_BASE_: "sub-1_stddev-1_batch-2_ga-4_val-test.yaml"
TEST:
  VAL_AS_TEST: True
MODEL:
  CONSISTENCY:
    LOSS_WEIGHT: 1.0
DESCRIPTION:
  BRIEF: "N2R - 1 subject recon / 13 subjects undersample, 12x undersampling w/ 2x4 grad accumulation - lambda = 1"
  EXP_NAME: "mridata_knee_2019/n2r_12x/sub-1_stddev-1_lambda-1"
  TAGS: ("n2r", "mridata_knee_2019", "sub-1", "12x", "grad_accumulation")
OUTPUT_DIR: "results://prelim-exps/n2r_12x/sub-1_stddev-1_lambda-1"
VERSION: 1