_BASE_: "sub-1_stddev-1.yaml"
DATALOADER:
  SUBSAMPLE_TRAIN:
    NUM_UNDERSAMPLED: 13  # 13 undersampled, 1 fully sampled
  NUM_WORKERS: 12
SOLVER:
  TRAIN_BATCH_SIZE: 2
  GRAD_ACCUM_ITERS: 8
TEST:
  VAL_AS_TEST: True
DESCRIPTION:
  BRIEF: "N2R 12x - 1 subjects"
  EXP_NAME: "mridata_knee_2019/n2r_12x/sub-1_stddev-1_2x8"
  TAGS: ("n2r", "mridata_knee_2019")
OUTPUT_DIR: "results://prelim-exps/n2r_12x/sub-1_stddev-1_2x8"
VERSION: 1