_BASE_: "template.yaml"
MODEL:
    UNET:
        CHANNELS: 256
OUTPUT_DIR: "results://fastmri_knee_mc_mini/n2r-unet-v1_4x/config-3"
DESCRIPTION:
  BRIEF: "N2R with 256 channel u-net, train batch size 1, 2x16 grad accum, 30 epochs, step decay at 10/20 epochs, lr=1e-4, no renormalize data"
  EXP_NAME: "fastmri_knee_mc_mini/unet/N2R/config-03"
  TAGS: ("fastmri_knee_mc_mini", "unet", "N2R", "sub10")
VERSION: 1