# 8 unrolled blocks, 512 feature maps each
_BASE_: "template.yaml"
MODEL:
  META_ARCHITECTURE: "GeneralizedUnrolledCNN"
  UNROLLED:
    NUM_UNROLLED_STEPS: 16
    NUM_RESBLOCKS: 2
    NUM_FEATURES: 128
    DROPOUT: 0.3
    CONV_BLOCK:
      ACTIVATION: "relu"
      NORM: "none"
      ORDER: ("act", "drop", "conv")
SOLVER:
  TRAIN_BATCH_SIZE: 2
OUTPUT_DIR: "results://arch_search/16x_feat-128_BS-2_drop-0.3"
VERSION: 1