# 8 unrolled blocks, 512 feature maps each
_BASE_: "template.yaml"
MODEL:
  META_ARCHITECTURE: "GeneralizedUnrolledCNN"
  UNROLLED:
    NUM_UNROLLED_STEPS: 20
    NUM_RESBLOCKS: 2
    NUM_FEATURES: 64
    DROPOUT: 0.
    CONV_BLOCK:
      ACTIVATION: "relu"
      NORM: "none"
      ORDER: ("act", "conv")
OUTPUT_DIR: "results://arch_search/20x_feat-64"
VERSION: 1