# 8 unrolled blocks, 512 feature maps each
_BASE_: "template.yaml"
MODEL:
  META_ARCHITECTURE: "GeneralizedUnrolledCNN"
  UNROLLED:
    NUM_UNROLLED_STEPS: 4
    NUM_RESBLOCKS: 2
    NUM_FEATURES: 128
    DROPOUT: 0.
    CONV_BLOCK:
      ACTIVATION: "relu"
      NORM: "none"
      ORDER: ("act", "conv")
OUTPUT_DIR: "results://arch_search/4x_feat-128"
VERSION: 1