# 8 unrolled blocks, 512 feature maps each
_BASE_: "8x_feat-128.yaml"
MODEL:
  META_ARCHITECTURE: "GeneralizedUnrolledCNN"
  UNROLLED:
    NUM_UNROLLED_STEPS: 8
    NUM_RESBLOCKS: 2
    NUM_FEATURES: 128
    DROPOUT: 0.
    CONV_BLOCK:
      ACTIVATION: "relu"
      NORM: "none"
      ORDER: ("conv", "act")
OUTPUT_DIR: "results://arch_search/8x_feat-128_conv-act"
VERSION: 1