_BASE_: "template.yaml"
DATALOADER:
  SUBSAMPLE_TRAIN:
    NUM_TOTAL: 1
DESCRIPTION:
  BRIEF: "Baseline (acceleration 16x) experiments with mridata.org 3D FSE dataset with maximum batch size - 1 subject"
  EXP_NAME: "mridata_knee_2019/baseline_16x_maxbatch/sub-1"
  TAGS: ("mridata_knee_2019", "unrolled", "baseline_16x")
SOLVER:
  CHECKPOINT_PERIOD: -20  # checkpoint every 20 epochs to reduce checkpointing frequency
TEST:
  EVAL_PERIOD: -20  # eval every 20 epochs to reduce eval frequency
OUTPUT_DIR: "results://prelim_exps/baseline_16x_maxbatch/sub-1"
VERSION: 1