_BASE_: "../n2r_template.yaml"
MODEL:
  CONSISTENCY:
    AUG:
      NOISE:
        STD_DEV: (1,)
AUG_TRAIN:
  UNDERSAMPLE:
    ACCELERATIONS: (6,)
AUG_TEST:
  UNDERSAMPLE:
    ACCELERATIONS: (6,)
DATALOADER:
  SUBSAMPLE_TRAIN:
    NUM_UNDERSAMPLED: 12
OUTPUT_DIR: "results://prelim-exps/n2r_6x/sub-2_stddev-1"
VERSION: 1