name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  Linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8"]
        
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
                    
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          make dev
      - name: Lint with isort, black, docformatter, flake8
        run: |
          make lint
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.7", "3.8", "3.9"]
        pytorch-version: ["latest"]
      include:
        - python-version: 3.8
          pytorch-version: latest
          torchmetrics-version: 0.6.0
        - python-version: 3.8
          pytorch-version: latest
          torchmetrics-version: "latest"
        - python-version: 3.7
          pytorch-version: 1.7.0
    env:
      PYTORCH: ${{ matrix.pytorch-version }}
      TORCHMETRICS: ${{ matrix.torchmetrics-version }}
    
    name: py${{ matrix.python-version  }}, pytorch-${{ matrix.torchmetrics-version }}, torchmetrics-${{ matrix.torchmetrics-version }}, ${{ matrix.os }}

    timeout-minutes: 50
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [[ $PYTORCH == "latest" || -z $PYTORCH ]]; then
            pip install torch torchvision
          else
            pip install torch==$PYTORCH torchvision
          fi
          pip install torchvision
          if [[ $TORCHMETRICS == "latest" || -z $TORCHMETRICS ]]; then
            pip install torchmetrics
          else
            pip install torchmetrics==$TORCHMETRICS
          fi
          make dev
          pip install -e '.[dev]'

      - name: Test with pytest
        run: |
          pip install pytest
          pip install pytest-cov
          make test-cov

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
