_BASE_: "../unrolled-v1_4x/template.yaml"
MODEL:
  META_ARCHITECTURE: "N2RModel"
  N2R:
    META_ARCHITECTURE: "GeneralizedUnrolledCNN"
  CONSISTENCY:
    LOSS_NAME: "l1"
    LOSS_WEIGHT: 0.1
    AUG:
      NOISE:
        STD_DEV: (0.2,)
DATALOADER:
  SAMPLER_TRAIN: "AlternatingSampler"
  ALT_SAMPLER:
    PERIOD_SUPERVISED: 1
    PERIOD_UNSUPERVISED: 1

# To set in experiment configs that inherit from this template
DESCRIPTION:
  BRIEF: ""
  EXP_NAME: ""
  TAGS: ()
OUTPUT_DIR: "" # Use prefix "results://fastmri_knee_mc_mini/n2r-unrolled-v1_4x"